### ISSUE TITLE
Issue with installation on Ubuntu

### ISSUE THREAD

**Issue by bednarczyk9** [diabaths/Crionic-Coin#5]
HI,

I'm following the instruction "Linux ( linux-gnu, usable on ANY linux ):"
I installed all dependencies on the beginning of the instruction and I receive error message for:
`bed9@bed9:~/Crionic-Coin$ cd depends/
bed9@bed9:~/Crionic-Coin/depends$ ls
builders      config.site.in  description.md  hosts     packages.md  README.md
config.guess  config.sub      funcs.mk        packages  patches
bed9@bed9:~/Crionic-Coin/depends$ make HOST=x86_64-pc-linux-gnu
make: *** No targets specified and no makefile found.  Stop.
`
When I try run the command: "make HOST=x86_64-pc-linux-gnu" for folder Cronic-Coin it returns the following error:
`bed9@bed9:~/Crionic-Coin$ sudo make HOST=x86_64-pc-linux-gnu
Making all in src
make[1]: Entering directory '/home/bed9/Crionic-Coin/src'
make[2]: Entering directory '/home/bed9/Crionic-Coin/src'
make[3]: Entering directory '/home/bed9/Crionic-Coin'
make[3]: Leaving directory '/home/bed9/Crionic-Coin'
  CXX      libbitcoin_server_a-httpserver.o
httpserver.cpp:73:10: error: ‘deque’ in namespace ‘std’ does not name a template type
   73 |     std::deque<std::unique_ptr<WorkItem>> queue;
      |          ^~~~~
httpserver.cpp:32:1: note: ‘std::deque’ is defined in header ‘<deque>’; did you forget to ‘#include <deque>’?
   31 | #include <support/events.h>
  +++ |+#include <deque>
   32 | 
httpserver.cpp: In member function ‘bool WorkQueue<WorkItem>::Enqueue(WorkItem*)’:
httpserver.cpp:91:13: error: ‘queue’ was not declared in this scope; did you mean ‘Enqueue’?
   91 |         if (queue.size() >= maxDepth) {
      |             ^~~~~
      |             Enqueue
httpserver.cpp:94:9: error: ‘queue’ was not declared in this scope; did you mean ‘Enqueue’?
   94 |         queue.emplace_back(std::unique_ptr<WorkItem>(item));
      |         ^~~~~
      |         Enqueue
httpserver.cpp: In member function ‘void WorkQueue<WorkItem>::Run()’:
httpserver.cpp:105:35: error: ‘queue’ was not declared in this scope; did you mean ‘Enqueue’?
  105 |                 while (running && queue.empty())
      |                                   ^~~~~
      |                                   Enqueue
httpserver.cpp:109:31: error: ‘queue’ was not declared in this scope; did you mean ‘Enqueue’?
  109 |                 i = std::move(queue.front());
      |                               ^~~~~
      |                               Enqueue
make[2]: *** [Makefile:6198: libbitcoin_server_a-httpserver.o] Error 1
make[2]: Leaving directory '/home/bed9/Crionic-Coin/src'
make[1]: *** [Makefile:10174: all-recursive] Error 1
make[1]: Leaving directory '/home/bed9/Crionic-Coin/src'
make: *** [Makefile:753: all-recursive] Error 1
bed9@bed9:~/Crionic-Coin$ sudo make HOST=x86_64-pc-linux-gnu
Making all in src
make[1]: Entering directory '/home/bed9/Crionic-Coin/src'
make[2]: Entering directory '/home/bed9/Crionic-Coin/src'
make[3]: Entering directory '/home/bed9/Crionic-Coin'
make[3]: Leaving directory '/home/bed9/Crionic-Coin'
  CXX      libbitcoin_server_a-httpserver.o
httpserver.cpp:73:10: error: ‘deque’ in namespace ‘std’ does not name a template type
   73 |     std::deque<std::unique_ptr<WorkItem>> queue;
      |          ^~~~~
httpserver.cpp:32:1: note: ‘std::deque’ is defined in header ‘<deque>’; did you forget to ‘#include <deque>’?
   31 | #include <support/events.h>
  +++ |+#include <deque>
   32 | 
httpserver.cpp: In member function ‘bool WorkQueue<WorkItem>::Enqueue(WorkItem*)’:
httpserver.cpp:91:13: error: ‘queue’ was not declared in this scope; did you mean ‘Enqueue’?
   91 |         if (queue.size() >= maxDepth) {
      |             ^~~~~
      |             Enqueue
httpserver.cpp:94:9: error: ‘queue’ was not declared in this scope; did you mean ‘Enqueue’?
   94 |         queue.emplace_back(std::unique_ptr<WorkItem>(item));
      |         ^~~~~
      |         Enqueue
httpserver.cpp: In member function ‘void WorkQueue<WorkItem>::Run()’:
httpserver.cpp:105:35: error: ‘queue’ was not declared in this scope; did you mean ‘Enqueue’?
  105 |                 while (running && queue.empty())
      |                                   ^~~~~
      |                                   Enqueue
httpserver.cpp:109:31: error: ‘queue’ was not declared in this scope; did you mean ‘Enqueue’?
  109 |                 i = std::move(queue.front());
      |                               ^~~~~
      |                               Enqueue
make[2]: *** [Makefile:6198: libbitcoin_server_a-httpserver.o] Error 1
make[2]: Leaving directory '/home/bed9/Crionic-Coin/src'
make[1]: *** [Makefile:10174: all-recursive] Error 1
make[1]: Leaving directory '/home/bed9/Crionic-Coin/src'
make: *** [Makefile:753: all-recursive] Error 1
`

Can you advice something, please?

**Comment by diabaths** [comment]
Pm in doscord

**Comment by bednarczyk9** [comment]
You can close the ticket. I installed the wallet on Windows.
